#!/bin/bash
usage()
{
	echo "mksrc usage:"
	echo "mksrc <dirname> <objname>"
	echo "      dirname: the storage path of C source and header file"
	echo "      objname: the file name of C source and header file"
}



show_info()
{
	echo "header_file:"${HEADERFILE}
	echo "source_file:"${SOURCEFILE}
}

gen_file_head()
{
	filename=$1
	defstr=`echo ${FILENAME^^}`
	defstr=$defstr"_H__"
	echo $defstr
	PREINFO=""
	PREINFO+="/****************************************Copyright (c)**************************************************\r\n"
	PREINFO+="**                                       God's harbor\r\n"
	PREINFO+="**\r\n"
	PREINFO+="**                                       yzfcer@163.com\r\n"
	PREINFO+="**\r\n"
	PREINFO+="**--------------File infomation-------------------------------------------------------------------------\r\n"
	PREINFO+="** FileName    : "${filename}"\r\n"
	PREINFO+="** Author      : "${AUTHOR}"\r\n"
	PREINFO+="** Last Date   : "${DATETIME}"\r\n"
	PREINFO+="** Description : \r\n"
	PREINFO+="**              \r\n"
	PREINFO+="**--------------History---------------------------------------------------------------------------------\r\n"
	PREINFO+="** Author      : "${AUTHOR}"\r\n"
	PREINFO+="** Version     : v1.0\r\n"
	PREINFO+="** Date        : "${DATETIME}"\r\n"
	PREINFO+="** Description : First version\r\n"
	PREINFO+="**\r\n"
	PREINFO+="**--------------Cureent version-------------------------------------------------------------------------\r\n"
	PREINFO+="** Modify      : "${AUTHOR}"\r\n"
	PREINFO+="** Date        : "${DATETIME}"\r\n"
	PREINFO+="** Description : \r\n"
	PREINFO+="**\r\n"
	PREINFO+="**------------------------------------------------------------------------------------------------------\r\n"
	PREINFO+="*******************************************************************************************************/\r\n"
	if [[ $filename == *".h" ]]
	then
		PREINFO+="#include \"wind_config.h\"\r\n"
		PREINFO+="#include \"wind_type.h\"\r\n"
		PREINFO+="#ifndef "$defstr"\r\n"
		PREINFO+="#define "$defstr"\r\n"
	elif [[ $filename == *".c" ]]
	then
		PREINFO+="#include \""${FILENAME}".h\"\r\n"
	fi
	PREINFO+="#ifdef __cplusplus\r\n"
	PREINFO+="extern \"C\" {\r\n"
	PREINFO+="#endif // #ifdef __cplusplus\r\n\r\n\r\n\r\n\r\n"
	PREINFO+="#ifdef __cplusplus\r\n"
	PREINFO+="}\r\n"
	PREINFO+="#endif // #ifdef __cplusplus\r\n"
	if [[ $filename == *".h" ]]
	then
		PREINFO+="#endif //#ifndef "$defstr"\r\n"
	fi
	
	echo -e "${PREINFO}"

}

if [ $# -lt 2 ]
then
	usage
	exit 0
fi
CUR_PATH=$(cd $(dirname $0); pwd)
STORPATH=$1
FILENAME=$2
#DATETIME=`date + "%Y/%m/%D %H:%M:%S"`
DATETIME=`date +%Y-%m-%d`
AUTHOR="Jason Zhou"
HEADERFILE=${STORPATH}/${FILENAME}.h
SOURCEFILE=${STORPATH}/${FILENAME}.c
PREINFO=""

show_info

touch ${HEADERFILE}
touch ${SOURCEFILE}

gen_file_head ${FILENAME}.h
echo -e "${PREINFO}" > ${HEADERFILE}

gen_file_head ${FILENAME}.c
echo -e "${PREINFO}" > ${SOURCEFILE}

